:encoding: utf-8
:lang: ja
:doctype: book
:toc: left
:toc-title: 目次
:toclevels: 3
:chapter-label:
:figure-caption: 図
:example-caption: 例
:table-caption: 表
:appendix-caption: 付録
:listing-caption: リスト
:sectnums:

= CommandPromptBat
これはWindowsバッチ集です。

= それぞれのバッチ説明
== CombineAndReplaceFiles.bat
=== 概要
複数ファイルの結合と置換を行います。
同ディレクトリ内にある、対象拡張子のファイル全てを結合します。  
ただし、ファイルエンコードは統一されている必要があります。
その際、文字列置換も可能です。  

=== 使用方法  
使用の際には、バッチを直接編集する必要があります。

==== ファイルエンコードを変更する場合
chcpから始まる行のコードポイントを任意の値に変更してください。

==== 対象拡張子変更を変更する場合
以下の行の"\*.txt"部分を変更してください。ただし、"*.bat"は指定できません(このbat自体が対象となってしまうため)。
```
type *.txt > %TMP_FILE%
```

==== 置換前後文字列を変更する場合
置換対象の文字列の指定箇所
```
set BEFORE_STR=before
```

置換後の文字列の指定箇所
```
set AFTER_STR=after
```

== TortoiseSvnUpdate.bat  
=== 概要
TortoiseSVNをGUIを使わずにSVN更新する。 

=== 使用方法
==== 更新対象ディレクトリを変更する場合  
以下の"対象ディレクトリ"を変更してください。
```
start TortoiseProc.exe /command:update /path:"対象ディレクトリ" /closeonend:3
```

=== 参考
http://tortoisesvn.net/docs/release/TortoiseSVN_ja/tsvn-automation.html

== shotdown.vbs  
=== 概要
確認ダイアログ付きの電源OFFスクリプト。 

=== 使用方法   
ダブルクリック等で、バッチを実行します。
確認ダイアログで"はい"を選択するとWindowsをシャットダウンします。

== switchingJava
=== 概要
Javaのバージョンを動的に変更します。
使用方法の詳細はswitchingJavaディレクトリのlink:/switchingJava/README.adoc[README]を参照してください。
